#!/bin/sh
cd "${0%/*}" || exit
. ${ML_CFD_BASE}/RunFunctions
#------------------------------------------------------------------------------

# dummy file for post-processing with paraview
touch post.foam

# mesh creation
runApplication blockMesh

# solver execution
runApplication pimpleFoam

#------------------------------------------------------------------------------
