#!/bin/sh
cd "${0%/*}" || exit        # Run from this directory
. ../../../../../functions  # singularity run functions
#------------------------------------------------------------------------------

cleanCase
rm -rf 0
rm -f trajectory.csv

#------------------------------------------------------------------------------
