#!/bin/bash
cd "${0%/*}" || exit
. ${ML_CFD_BASE}/RunFunctions
#------------------------------------------------------------------------------

# dummy file for post-processing with paraview
touch post.foam

# mesh creation
runApplication blockMesh

# set inlet velocity
cp -r 0.org 0
runApplication setExprBoundaryFields

# decompose, initialize, and run (parallel)
runApplication decomposePar
runParallel renumberMesh -overwrite
runParallel potentialFoam -writephi
runParallel $(getApplication)

#------------------------------------------------------------------------------
